### ISSUE TITLE
Workspace output list not supported?

### ISSUE THREAD

**Issue by SylvainMartel** [hashicorp/tfc-workflows-gitlab#20]
Hi, we just started using this to integrate with our gitlab and I was looking for a way to capture the workspace output to then feed into an ansible script.

I see that v1.1.1 was supposed to add Workspace Output support, but looks like only the github template really got support for it? 

I see no mention of this feature in the template for gitlab, am I overlooking something?

Thanks

**Comment by SylvainMartel** [comment]
Based on the tfc-workflows-github repo, I've added support to the gitlab Base template.  I can make a PR if you want

**Comment by zainq11** [comment]
Thank you for your contribution @SylvainMartel. We will review the PR. I will also checkup on why this support was not added to the gitlab templates.

**Comment by mjyocca** [comment]
Closing since this was added. Thanks for your contribution and raising this @SylvainMartel.
