### ISSUE TITLE
error uploading configuration version to Terraform Cloud: resource not found

### ISSUE THREAD

**Issue by ikunduraci** [hashicorp/tfc-workflows-gitlab#7]
Hey team,

API-driven workspace named `myworkspace` created in TFC.  Have a simple repo with a single `main.tf` file in the root of the repo (output shown below). Just using the template `.gitlab-ci.yml` in this repo, having issues with upload.

Gitlab runner using k8s executor. 

```
Executing "step_script" stage of the job script 00:01
$ pwd
/builds/<redacted>/projects/project1
$ ls
README.md
main.tf
```

```
$ tfci -hostname=$TF_CLOUD_HOSTNAME  -token=$TF_API_TOKEN -organization=$TF_CLOUD_ORGANIZATION upload -workspace=$TF_WORKSPACE -speculative=$SPECULATIVE -directory=$TF_DIRECTORY
2023-05-26T05:05:22.578Z [INFO]  tfci: version: v1.0.0
2023-05-26T05:05:22.578Z [INFO]  tfci: Go runtime version: go1.18.10
2023-05-26T05:05:22.579Z [DEBUG] tfci: Preparing runner
2023-05-26T05:05:22.579Z [DEBUG] tfci: Command argument count: 7
2023-05-26T05:05:22.579Z [DEBUG] tfci: Subcommand arg count: 4 for organization: <redacted>
2023-05-26T05:05:22.579Z [DEBUG] tfci: Initializing terraform cloud client, host: app.terraform.io
2023-05-26T05:05:22.579Z [DEBUG] tfci: token has been set
2023-05-26T05:05:23.871Z [DEBUG] tfci: Running command
2023-05-26T05:05:23.872Z [DEBUG] tfci: uploading configuration with, workspace: myworkspace, directory: , speculative: false
2023-05-26T05:05:23.872Z [DEBUG] tfci: target directory for configuration upload: /builds/<redacted>/projects/project1
error uploading configuration version to Terraform Cloud: resource not found
2023-05-26T05:05:24.496Z [INFO]  tfci: Gitlab flushing output
{
  "status": "Error"
}
```
Tried setting `TF_DIRECTORY="./"` etc; however can't seem to make it go.

Cheers

**Comment by zainq11** [comment]
Hi @ikunduraci ,
Thanks for trying this out. Regarding this error:
```
error uploading configuration version to Terraform Cloud: resource not found
```
This happens when either the workspace or organization is not found in TFC. Would you be able to verify that the API driven workspace "myworkspace" shows up as expected in the TFC UI?

**Comment by ikunduraci** [comment]
Hi @zainq11,

Yes - the workspace was freshly created through the UI, and obviously shows up in the UI.

**Comment by zainq11** [comment]
Thank you for confirming. I noticed that the log files have the organization redacted, which does not necessarily indicate a problem.
Would you be able to provide a little more context on how you are defining variables in your test. Is it done via the Gitlab UI or k8s executor config or a combination of both? We did not test our workflows with a k8s executor. There might be something unique with this flow that is causing this behavior. I really appreciate the time taken to test this out.

**Comment by ikunduraci** [comment]
Variables are set via the Gitlab UI. I’ve also tested using the docker executor in a different org, same error. As a side note, i've redacted the organisation name from the logs for security reasons.

**Comment by ikunduraci** [comment]
Hi @zainq11 

I managed to resolve my issue. The token used was the organisation token, which doesn't have permissions to create config. versions. I switched to a team token and all systems are go.

Thanks for your help!

**Comment by zainq11** [comment]
Glad you were able to figure it out! Thanks so much for taking the time to try our tooling.
